export const Products = [
  {
    id: 0,
    name: "Macbook PRO",
    image: "/images/main-section/imac-laptop.png",
    category: "laptops",
    price: 1899,
    oldPrice: 1999,
    featured: true,
  },
  {
    id: 1,
    name: "Apple Iphone 12 Pro",
    image: "/images/main-section/iphone.png",
    category: "Mobile Phone",
    price: 899,
    oldPrice: 999,
    featured: true,
  },
  {
    id: 2,
    name: "Sony MDR-ZX110",
    image: "/images/main-section/sony-headphones.png",
    category: "headphone",
    price: 399,
    oldPrice: 499,
    featured: true,
  },
  {
    id: 3,
    name: "Ipad Pro",
    image: "/images/main-section/ipad-pro.png",
    category: "Mobile Phone",
    price: 899,
    oldPrice: 999,
    featured: false,
  },

  {
    id: 4,
    name: "Amazon Device",
    image: "/images/main-section/alexa.png",
    category: "amazon devices",
    price: 399,
    oldPrice: 999,
    featured: false,
  },

  {
    id: 5,
    name: "Apple Watch",
    image: "/images/main-section/watch-sm.png",
    category: "watches",
    price: 599,
    oldPrice: 699,
    featured: false,
  },

  {
    id: 6,
    name: "Nike",
    image: "/images/hero-section/hero.png",
    category: "shoes",
    price: 599,
    oldPrice: 699,
    trending: true,
  },
  {
    id: 7,
    name: "Apple Imac",
    image: "/images/hero-section/imac-pro.png",
    category: "imac",
    price: 599,
    oldPrice: 699,
    trending: true,
  },
  {
    id: 8,
    name: "Smart Watch",
    image: "/images/hero-section/clay-apple-watch.png",
    category: "watches",
    price: 599,
    oldPrice: 699,
    trending: true,
  },

  {
    id: 9,
    name: "Nike Shoes",
    image: "/images/main-section/shoe1.png",
    category: "shoes",
    price: 599,
    oldPrice: 699,
    flashSale: true,
  },
  {
    id: 10,
    name: "Nike Shoes",
    image: "/images/main-section/shoe2.png",
    category: "shoes",
    price: 599,
    oldPrice: 699,
    flashSale: true,
  },
  {
    id: 11,
    name: "Nike Shoes",
    image: "/images/main-section/shoe3.png",
    category: "shoes",
    price: 599,
    oldPrice: 699,
    flashSale: true,
  },
  {
    id: 12,
    name: "4K LED TV",
    image: "/images/main-section/led-tv2.png",
    category: "electronic device",
    price: 1999,
    oldPrice: 2999,
    deals: true,
  },
];
